import { GoogleGenerativeAI } from "@google/generative-ai";
import { type Message } from "@/components/ChatPanel";
import { type LegalSection } from "@/components/LegalOutputPanel";

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const genAI = new GoogleGenerativeAI(API_KEY || "");

const SYSTEM_PROMPT = `You are e-Vakil, an expert AI Legal Counsel specializing in Indian Law (BNS, IPC, CRPC, Motor Vehicles Act, etc.).
Your goal is to provide highly accurate, hallucination-free legal analysis based on the user's grievance.

When the user explains a situation, you must return a strictly formatted JSON object exactly matching this schema:
{
  "replyText": "A 2-3 sentence conversational response directly addressing the user and summarizing the action. If asking follow up questions, ask them here.",
  "sections": [
    {
      "id": "autogenerated-unique-id",
      "sectionName": "Name of the Law/Section (e.g., Section 279 IPC)",
      "confidence": 85,
      "applicableLaw": "Detailed quote or summary of the legal provision.",
      "explanation": "Why this law applies to their specific case.",
      "punishment": "Potential fines, jail time, or legal consequence.",
      "whatToDo": "Immediate actionable steps they must take.",
      "whereToFile": "Exactly which authority, court, or police station they should approach."
    }
  ]
}

If no specific laws are found, return an empty array for sections, and just converse using replyText.`;

export async function generateLegalResponse(
  history: Message[],
  currentInput: string
): Promise<{ replyText: string; sections: LegalSection[] }> {
  if (!API_KEY) {
    console.error("Missing VITE_GEMINI_API_KEY in .env");
    return {
      replyText: "Configuration Error: API Key missing. Please check your .env file.",
      sections: []
    };
  }

  try {
    const model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash",
      systemInstruction: SYSTEM_PROMPT,
      generationConfig: {
        temperature: 0.1,
        responseMimeType: "application/json",
      },
    });

    const chatHistory = history.map((msg) => ({
      role: msg.role === "assistant" ? "model" : "user",
      parts: [{ text: msg.content }],
    }));

    const chat = model.startChat({
      history: chatHistory,
    });

    let textObj = "";
    let retries = 3;
    
    // Automatic retry logic for 503 High Demand Errors
    while (retries > 0) {
      try {
        const result = await chat.sendMessage(currentInput);
        textObj = result.response.text();
        break; // Success!
      } catch (err: any) {
        if (err.status === 503 && retries > 1) {
          retries--;
          await new Promise(resolve => setTimeout(resolve, 2000)); // Wait 2 seconds before retry
          continue;
        }
        throw err; // Rethrow if it's not a 503 or we're out of retries
      }
    }

    const parsed = JSON.parse(textObj);

    return {
      replyText: parsed.replyText || "I have analyzed your situation.",
      sections: parsed.sections
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ? parsed.sections.map((s: any, idx: number) => ({
            ...s,
            id: `gemini-sec-${idx}-${Date.now()}`
          }))
        : [],
    };
  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    return {
      replyText: `Error Details: ${error?.message || "Unknown Error"}`,
      sections: [],
    };
  }
}
